apiVersion: v1
kind: Service
metadata:
  name: finhelm-api
  namespace: finhelm
spec:
  type: ClusterIP
  selector:
    app: finhelm
    component: api
  ports:
    - name: http
      port: 80
      targetPort: http
